version: 2.1
jobs:
  build:
    working_directory: ~/app-server/
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
         key: composer-v1-{{ checksum "./app-server/composer.lock" }}
      - run: 
         command: composer install -n --prefer-dist
         working_directory: ./app-server/
      - save_cache:
          key: composer-v1-{{ checksum "./app-server/composer.lock" }}
          paths:
             - vendor
      - restore_cache:
          key: npm-v1-{{ checksum "./app-server/package-lock.json" }}       
      - run:
          name: npm ci
          working_directory: ./app-server/
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi 
      - save_cache:
          key: npm-v1-{{ checksum "./app-server/package-lock.json" }}
          paths:
            - node_modules
      - run: 
         command: npm run dev
         working_directory: ./app-server/
      - run:
          name: php test
          command: vendor/bin/phpunit
          working_directory: ./app-server/

  deploy:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - add_ssh_keys
      - run:
          name: deploy
          command: |
            ssh -o StrictHostKeyChecking=no -t webapp@${HOST_NAME} "cd laravel-app && \
              git pull origin master && \
              composer install -n --no-dev --prefer-dist && \
              npm ci && \
              npm run prod && \
              php artisan migrate --force && \
              php artisan config:cache"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
     