version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - run:
          command: composer install -n --prefer-dist
          working_directory: ./app-server/
      - run:
          command: npm ci
          working_directory: ./app-server/
      - run:
          command: npm run dev
          working_directory: ./app-server/
      - run:
          name: php test
          command: vendor/bin/phpunit
          working_directory: ./app-server/