version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - run:
          command: composer install -n --prefer-dist
      - run:
          name: install
          command: npm ci
      - run:
          command: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit