version: 2.1
jobs:
  build:
    working_directory: ~/app-server/
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
         key: composer-v1-{{ checksum "composer.lock" }}
         working_directory: ./app-server/
      - run: 
         command: composer install -n --prefer-dist
         working_directory: ./app-server/
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          working_directory: ./app-server/
          paths:
             - vendor
      - run:
         command: npm ci
         working_directory: ./app-server/
      - run: 
         command: npm run dev
         working_directory: ./app-server/
      - run:
          name: php test
          command: vendor/bin/phpunit
          working_directory: ./app-server/
     